stages:
- build
- lint
- test
- package
- deploy

cache:
  untracked: true
  key: mifi-backend
  paths:
  - target/

build:
  stage: build
  image: mseravalli/sbt:1.0.1
  script:
  - sbt clean
  - sbt compile
  - sbt dist

lint:
  stage: lint
  image: alpine
  script:
  - echo "TODO"

test:
  stage: test
  image: alpine
  script:
  - echo "TODO"
   #  - sbt clean
   # - sbt test
   # - sbt coverage test coverageReport

package:
  stage: package
  image: docker:latest
  script:
    - docker build -t mseravalli/mifi-backend:latest .

deploy:
  stage: deploy
  image: alpine
  script:
  - echo "TODO"

