image: hseeberger/scala-sbt

stages:
  - build
  - lint
  - test
  - package
  - deploy

before_script:
  - sbt sbt-version

build:
  stage: build
  script:
    - sbt clean
    - sbt compile

lint:
  stage: lint
  script:
    - echo "TODO"

test:
  stage: test
  script:
    - sbt clean
    - sbt coverage test coverageReport

package:
  stage: package
  script:
    - build-image.sh

deploy:
  stage: deploy
  script:
    - echo "TODO"

