image: mseravalli/sbt:1.0.1

stages:
- build
- lint
- test
- package
- deploy

build:
  stage: build
  script:
  - sbt clean
  - sbt compile

lint:
  stage: lint
  script:
  - echo "TODO"

test:
  stage: test
  script:
  - echo "TODO"
   #  - sbt clean
   # - sbt test
   # - sbt coverage test coverageReport

package:
  stage: package
  script:
    - build-image.sh

deploy:
  stage: deploy
  script:
  - echo "TODO"

