language: scala
scala:
  - 2.10.4
  - 2.11.2

services:
  - docker

before_script:
  - npm install -g bower
  - bower install

script:
  - sbt compile
  - sbt test


before_deploy:
  - sbt dist
  - export VERSION=`sbt version | awk 'END {print $2}' | sed 's/\[0m//g' | sed 's/^.//' | sed 's/.$//'`
  - cat Dockerfile | awk 'NR==4 {print "ENV VERSION '"$VERSION"'"} 1' > tmp.tmp && mv tmp.tmp Dockerfile
  - docker build -t mi-fi:$VERSION .

