branches:
  only:
    - master

language: scala
scala:
  - 2.10.4
  - 2.11.2

services:
  - docker

before_script:
  - npm install -g bower
  - bower install

script:
  - sbt compile
  - sbt test

after_script:
  - sbt dist
  - export VERSION=`grep 'version :=' build.sbt | awk '{print $3}' | sed 's/\"//g'`
  - unzip ./target/universal/mi-fi-$VERSION.zip -d ./target/universal/
  - mv target/universal/mi-fi-$VERSION target/universal/mi-fi
  - docker build -t mseravalli/mi-fi:$VERSION .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push mseravalli/mi-fi
