substitutions:
  _IMAGE_NAME: eu.gcr.io/devar-p/mifi-backend-builder # default value

steps:
- id: 'tar'
  name: 'ubuntu'
  args: ['tar', 'cf', 'mifi.tar', '.' ]

- id: 'docker-build-latest'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE_NAME}:latest', '-f', 'builder.Dockerfile', '.']

images: [
  '${_IMAGE_NAME}:latest'
]

