substitutions:
  _IMAGE_NAME: eu.gcr.io/devar-p/mifi-backend-builder # default value

- id: 'docker-build-latest'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE_NAME}:latest', '-f', 'builder.Dockerfile', '.']

images: [
  '${_IMAGE_NAME}:latest'
]

