steps:
- id: 'build'
  name: 'mseravalli/sbt:latest'
  args: ['bash', 'activator', 'clean', 'compile', 'dist']

- id: 'release'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'mseravalli/mifi-backend:latest', '.']

