steps:
- id: 'compile'
  name: 'mseravalli/sbt:latest'
  args: ['bash', 'activator', 'clean', 'compile']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'mseravalli/mifi-backend:latest', '.']

