substitutions:
  _IMAGE_NAME: eu.gcr.io/devar-p/mifi-backend # default value
  _BUILDER_IMAGE: mseravalli/mifi-backend-builder # default value

steps:
- id: 'clean'
  name: '${_BUILDER_IMAGE}'
  args: ['bash', 'activator', '--info', 'clean']

- id: 'build'
  name: '${_BUILDER_IMAGE}'
  args: ['bash', 'activator', '--info', 'compile']

- id: 'setup integration environment'
  name: 'docker/compose:1.15.0'
  args: ['up', '-d']

- id: 'integration test'
  name: '${_BUILDER_IMAGE}'
  args: ['bash', 'activator', '--info', 'test']

- id: 'package'
  name: '${_BUILDER_IMAGE}'
  args: ['bash', 'activator', '--info', 'dist']

- id: 'extract'
  name: '${_BUILDER_IMAGE}'
  args: ['bash', 'extract-dist.sh']

- id: 'docker-build-latest'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE_NAME}:latest', '.']

# - id: 'docker-push-latest'
#   name: 'gcr.io/cloud-builders/docker'
#   args: ['push', '${_IMAGE_NAME}:latest']

# - id: 'docker-tag-version'
#   name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', '${_IMAGE_NAME}:${TAG_NAME}', '.']

# - id: 'docker-push-version'
#   name: 'gcr.io/cloud-builders/docker'
#   args: ['push', '${_IMAGE_NAME}:${TAG_NAME}']

images: [
  '${_IMAGE_NAME}:latest'
]
