steps:
- id: 'clean'
  name: 'mseravalli/mifi-builder'
  args: ['bash', 'activator', '--info', 'clean']

- id: 'build'
  name: 'mseravalli/mifi-builder'
  args: ['bash', 'activator', '--info', 'dist']

- id: 'extract'
  name: 'mseravalli/mifi-builder'
  args: ['bash', 'extract-dist.sh']

- id: 'docker-build-latest'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'mseravalli/mifi-backend:latest', '.']

- id: 'docker-push-latest'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'mseravalli/mifi-backend:latest', '.']

- id: 'docker-tag-version'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'mseravalli/mifi-backend:${TAG_NAME}', '.']

- id: 'docker-push-version'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'mseravalli/mifi-backend:${TAG_NAME}', '.']
