FROM java:jdk-alpine

RUN apk add --no-cache bash
RUN mkdir -p /opt/mi-fi 
COPY ./ /opt/mi-fi/
RUN cd /opt/mi-fi && /bin/bash /opt/mi-fi/activator dist
RUN mv /opt/mi-fi/target/universal/mi-fi-0.4.1.zip /opt/
RUN unzip /opt/mi-fi-0.4.1.zip -d /opt/
RUN rm -rf /opt/mi-fi
RUN ln -s /opt/mi-fi-0.4.1 /opt/mi-fi
RUN rm -rf /root/.ivy2 /root/.sbt

EXPOSE 9000

ENTRYPOINT /opt/mi-fi/bin/mi-fi

MAINTAINER Marco Seravalli <marco.seravalli@gmail.com>
